In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [3]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

In [4]:
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255

m = X_train.shape[1]

In [5]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2 
    
def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z), axis = 0)

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2
    
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, axis = 0)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, axis = 0)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [6]:
#For getting accuracy % for the model created:

def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

#---------------------------------------------

def gradient_descent(X, Y, interations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(interations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        
        if (i % 10 == 0):
            print('Iteration: ', i)
            print('Accuracy: ', get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [7]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 100, 0.1)

Iteration:  0
[3 5 9 ... 3 9 3] [3 0 5 ... 6 2 0]
Accuracy:  0.11192682926829269
Iteration:  10
[3 4 1 ... 3 7 0] [3 0 5 ... 6 2 0]
Accuracy:  0.188
Iteration:  20
[6 0 1 ... 6 7 0] [3 0 5 ... 6 2 0]
Accuracy:  0.2594390243902439
Iteration:  30
[6 0 1 ... 6 6 0] [3 0 5 ... 6 2 0]
Accuracy:  0.31209756097560976
Iteration:  40
[6 0 1 ... 6 6 0] [3 0 5 ... 6 2 0]
Accuracy:  0.3571951219512195
Iteration:  50
[6 0 1 ... 6 6 0] [3 0 5 ... 6 2 0]
Accuracy:  0.4277073170731707
Iteration:  60
[6 0 1 ... 6 6 0] [3 0 5 ... 6 2 0]
Accuracy:  0.501780487804878
Iteration:  70
[2 0 1 ... 2 6 0] [3 0 5 ... 6 2 0]
Accuracy:  0.5416585365853659
Iteration:  80
[2 0 5 ... 2 2 0] [3 0 5 ... 6 2 0]
Accuracy:  0.5772439024390243
Iteration:  90
[2 0 5 ... 2 2 0] [3 0 5 ... 6 2 0]
Accuracy:  0.6070975609756097
